//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Comment_ID { get; set; }
        public int Movie_ID { get; set; }
        public int Customer_ID { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
