//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Ticket_ID { get; set; }
        public int Showtime_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public int Seat_ID { get; set; }
        public int Ticket_Type_ID { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual Showtime Showtime { get; set; }
        public virtual Ticket_Type Ticket_Type { get; set; }
    }
}
