//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_VIEW
    {
        public string Client { get; set; }
        public string Movie { get; set; }
        public string Showtime { get; set; }
        public int Ticket_Price { get; set; }
        public string Status { get; set; }
        public string Seat { get; set; }
        public int Screen_ID { get; set; }
        public string Transaction { get; set; }
    }
}
