//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOWTIME_VIEW
    {
        public string Movie { get; set; }
        public int Duration { get; set; }
        public Nullable<int> Age_Category { get; set; }
        public string Director { get; set; }
        public string Description { get; set; }
        public string Genre { get; set; }
        public int Screen { get; set; }
        public string Technology { get; set; }
        public string Date { get; set; }
    }
}
